### ISSUE TITLE
Speed up Travis CI tests

### ISSUE THREAD

**Issue by martintoreilly** [alan-turing-institute/SHEEP#60]
Tests on Travis take 10-15 mins to run rather than a few minutes due to having to build everything from source.

Look at Travis' [caching support](https://docs.travis-ci.com/user/caching).
- Looks like we can cache [arbitrary directories](https://docs.travis-ci.com/user/caching#Arbitrary-directories) or use certain language-specific cache methods (e.g. [ccache for C/C++](https://docs.travis-ci.com/user/caching#ccache-cache))
- For OSX builds, `ccache` needs to be installed separately 
- To get caching working on R, we needed to [ensure that we were using Travis' dockerised workers](https://docs.travis-ci.com/user/languages/r/#Basic-configuration), which involved setting `sudo: false` in `.travis.yml`. This may or may not have any affect on C/C++ builds or `ccache`.
- Example [.travis.yml file](https://gist.github.com/Kimundi/10d299e905941e82bee4969acc7b64a8) that looks like it's doing purely directory-based dependency caching (it does set `sudo: false`).

**Comment by tomaslaz** [comment]
Down to ~9 mins.
